const fs = require('fs');

function patchPulseDemoEditor(path) {
  let content = fs.readFileSync(path, 'utf8');

  // Fix openLinkModal for EditableHeading
  content = content.replace(
    `  const openLinkModal = () => {\n    const el = headingRef.current;\n    if (!el) return;\n\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalOpen(true);\n  };`,
    `  const openLinkModal = () => {\n    skipBlurRef.current = true;\n    const el = headingRef.current;\n    if (!el) return;\n\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      setLinkModalTarget(existingLink.target);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalTarget('');\n    setLinkModalOpen(true);\n  };`
  );

  // Fix openLinkModal for EditableText
  content = content.replace(
    `  const openLinkModal = () => {\n    const el = textRef.current;\n    if (!el) return;\n\n    // Check if cursor is inside an existing link\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    // Save the selection range before modal steals focus\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalOpen(true);\n  };`,
    `  const openLinkModal = () => {\n    skipBlurRef.current = true;\n    const el = textRef.current;\n    if (!el) return;\n\n    // Check if cursor is inside an existing link\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      setLinkModalTarget(existingLink.target);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    // Save the selection range before modal steals focus\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalTarget('');\n    setLinkModalOpen(true);\n  };`
  );

  // Fix openLinkModal for EditableBlockquote
  content = content.replace(
    `  const openLinkModal = () => {\n    const el = quoteRef.current;\n    if (!el) return;\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalOpen(true);\n  };`,
    `  const openLinkModal = () => {\n    skipBlurRef.current = true;\n    const el = quoteRef.current;\n    if (!el) return;\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      setLinkModalTarget(existingLink.target);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalTarget('');\n    setLinkModalOpen(true);\n  };`
  );

  // Fix LinkModal JSX calls
  content = content.replace(
    /<LinkModal\n        isOpen=\{linkModalOpen\}\n        onClose=\{\(\) => setLinkModalOpen\(false\)\}\n        onConfirm=\{handleLinkConfirm\}\n        onRemove=\{linkModalUrl \? handleLinkRemove : undefined\}\n        defaultText=\{linkModalText\}\n        defaultUrl=\{linkModalUrl\}\n        defaultRel=\{linkModalRel\}\n      \/>/g,
    `<LinkModal\n        isOpen={linkModalOpen}\n        onClose={() => { skipBlurRef.current = false; setLinkModalOpen(false); }}\n        onConfirm={handleLinkConfirm}\n        onRemove={linkModalUrl ? handleLinkRemove : undefined}\n        defaultText={linkModalText}\n        defaultUrl={linkModalUrl}\n        defaultRel={linkModalRel}\n        defaultTarget={linkModalTarget}\n      />`
  );

  // Fix RefModal JSX calls
  content = content.replace(
    /<RefModal\n        isOpen=\{refModalOpen\}\n        onClose=\{\(\) => setRefModalOpen\(false\)\}\n        onConfirm=\{handleRefConfirm\}\n        onRemove=\{existingRefRef\.current \? handleRefRemove : undefined\}\n        defaultUrl=\{refModalUrl\}\n        defaultText=\{refModalText\}\n        defaultStyle=\{refModalStyle\}\n      \/>/g,
    `<RefModal\n        isOpen={refModalOpen}\n        onClose={() => { skipBlurRef.current = false; setRefModalOpen(false); }}\n        onConfirm={handleRefConfirm}\n        onRemove={existingRefRef.current ? handleRefRemove : undefined}\n        defaultUrl={refModalUrl}\n        defaultText={refModalText}\n        defaultStyle={refModalStyle}\n        defaultTarget={refModalTarget}\n      />`
  );

  fs.writeFileSync(path, content);
}

function patchStudioBlockCanvas(path) {
  let content = fs.readFileSync(path, 'utf8');

  // Fix EditableText openLinkModal: add setLinkModalTarget
  content = content.replace(
    `  const openLinkModal = () => {\n    skipBlurRef.current = true;\n    const el = textRef.current;\n    if (!el) return;\n\n    // Check if cursor is inside an existing link\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    // Save the selection range before modal steals focus\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalOpen(true);\n  };`,
    `  const openLinkModal = () => {\n    skipBlurRef.current = true;\n    const el = textRef.current;\n    if (!el) return;\n\n    // Check if cursor is inside an existing link\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      setLinkModalTarget(existingLink.target);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    // Save the selection range before modal steals focus\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalTarget('');\n    setLinkModalOpen(true);\n  };`
  );

  // Fix EditableBlockquote openLinkModal: add setLinkModalTarget
  content = content.replace(
    `  const openLinkModal = () => {\n    skipBlurRef.current = true;\n    const el = quoteRef.current;\n    if (!el) return;\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalOpen(true);\n  };`,
    `  const openLinkModal = () => {\n    skipBlurRef.current = true;\n    const el = quoteRef.current;\n    if (!el) return;\n    const existingLink = getLinkAtCursor(el);\n    if (existingLink) {\n      setLinkModalText(existingLink.text);\n      setLinkModalUrl(existingLink.url);\n      setLinkModalRel(existingLink.rel);\n      setLinkModalTarget(existingLink.target);\n      existingLinkRef.current = existingLink;\n      savedRangeRef.current = null;\n      setLinkModalOpen(true);\n      return;\n    }\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingLinkRef.current = null;\n    setLinkModalText(selectedText);\n    setLinkModalUrl('');\n    setLinkModalRel('');\n    setLinkModalTarget('');\n    setLinkModalOpen(true);\n  };`
  );

  // Fix EditableText openRefModal: add setRefModalTarget
  content = content.replace(
    `  const openRefModal = () => {\n    const el = textRef.current;\n    if (!el) return;\n    skipBlurRef.current = true;\n    const existingRef = getRefAtCursor(el);\n    if (existingRef) {\n      setRefModalUrl(existingRef.url || '');\n      setRefModalText(existingRef.text || '');\n      setRefModalStyle(existingRef.style);\n      existingRefRef.current = existingRef;\n      savedRangeRef.current = null;\n      setRefModalOpen(true);\n      return;\n    }\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingRefRef.current = null;\n    setRefModalText(selectedText);\n    setRefModalUrl('');\n    setRefModalStyle('numeric');\n    setRefModalOpen(true);\n  };`,
    `  const openRefModal = () => {\n    const el = textRef.current;\n    if (!el) return;\n    skipBlurRef.current = true;\n    const existingRef = getRefAtCursor(el);\n    if (existingRef) {\n      setRefModalUrl(existingRef.url || '');\n      setRefModalText(existingRef.text || '');\n      setRefModalStyle(existingRef.style);\n      setRefModalTarget(existingRef.target || '');\n      existingRefRef.current = existingRef;\n      savedRangeRef.current = null;\n      setRefModalOpen(true);\n      return;\n    }\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingRefRef.current = null;\n    setRefModalText(selectedText);\n    setRefModalUrl('');\n    setRefModalStyle('numeric');\n    setRefModalTarget('');\n    setRefModalOpen(true);\n  };`
  );

  // Fix EditableBlockquote openRefModal: add setRefModalTarget
  content = content.replace(
    `  const openRefModal = () => {\n    const el = quoteRef.current;\n    if (!el) return;\n    skipBlurRef.current = true;\n    const existingRef = getRefAtCursor(el);\n    if (existingRef) {\n      setRefModalUrl(existingRef.url || '');\n      setRefModalText(existingRef.text || '');\n      setRefModalStyle(existingRef.style);\n      existingRefRef.current = existingRef;\n      savedRangeRef.current = null;\n      setRefModalOpen(true);\n      return;\n    }\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingRefRef.current = null;\n    setRefModalText(selectedText);\n    setRefModalUrl('');\n    setRefModalStyle('numeric');\n    setRefModalOpen(true);\n  };`,
    `  const openRefModal = () => {\n    const el = quoteRef.current;\n    if (!el) return;\n    skipBlurRef.current = true;\n    const existingRef = getRefAtCursor(el);\n    if (existingRef) {\n      setRefModalUrl(existingRef.url || '');\n      setRefModalText(existingRef.text || '');\n      setRefModalStyle(existingRef.style);\n      setRefModalTarget(existingRef.target || '');\n      existingRefRef.current = existingRef;\n      savedRangeRef.current = null;\n      setRefModalOpen(true);\n      return;\n    }\n    const selection = window.getSelection();\n    const selectedText = selection?.toString().trim();\n    if (!selectedText) return;\n    if (selection && selection.rangeCount > 0) {\n      savedRangeRef.current = selection.getRangeAt(0).cloneRange();\n    }\n    existingRefRef.current = null;\n    setRefModalText(selectedText);\n    setRefModalUrl('');\n    setRefModalStyle('numeric');\n    setRefModalTarget('');\n    setRefModalOpen(true);\n  };`
  );

  // Fix LinkModal JSX: add defaultTarget to existing multiline onClose
  content = content.replace(
    /<LinkModal\n        isOpen=\{linkModalOpen\}\n        onClose=\{\(\) => \{\n          skipBlurRef\.current = false;\n          setLinkModalOpen\(false\);\n        \}\}\n        onConfirm=\{handleLinkConfirm\}\n        onRemove=\{linkModalUrl \? handleLinkRemove : undefined\}\n        defaultText=\{linkModalText\}\n        defaultUrl=\{linkModalUrl\}\n        defaultRel=\{linkModalRel\}\n      \/>/g,
    `<LinkModal\n        isOpen={linkModalOpen}\n        onClose={() => {\n          skipBlurRef.current = false;\n          setLinkModalOpen(false);\n        }}\n        onConfirm={handleLinkConfirm}\n        onRemove={linkModalUrl ? handleLinkRemove : undefined}\n        defaultText={linkModalText}\n        defaultUrl={linkModalUrl}\n        defaultRel={linkModalRel}\n        defaultTarget={linkModalTarget}\n      />`
  );

  // Fix RefModal JSX: add defaultTarget to existing multiline onClose
  content = content.replace(
    /<RefModal\n        isOpen=\{refModalOpen\}\n        onClose=\{\(\) => \{\n          skipBlurRef\.current = false;\n          setRefModalOpen\(false\);\n        \}\}\n        onConfirm=\{handleRefConfirm\}\n        onRemove=\{existingRefRef\.current \? handleRefRemove : undefined\}\n        defaultUrl=\{refModalUrl\}\n        defaultText=\{refModalText\}\n        defaultStyle=\{refModalStyle\}\n      \/>/g,
    `<RefModal\n        isOpen={refModalOpen}\n        onClose={() => {\n          skipBlurRef.current = false;\n          setRefModalOpen(false);\n        }}\n        onConfirm={handleRefConfirm}\n        onRemove={existingRefRef.current ? handleRefRemove : undefined}\n        defaultUrl={refModalUrl}\n        defaultText={refModalText}\n        defaultStyle={refModalStyle}\n        defaultTarget={refModalTarget}\n      />`
  );

  fs.writeFileSync(path, content);
}

patchPulseDemoEditor('C:/Users/z0512/Desktop/pulse/apps/website/app/demo/PulseDemoEditor.tsx');
patchStudioBlockCanvas('C:/Users/z0512/Desktop/pulse/apps/website/app/components/StudioBlockCanvas.tsx');
console.log('Done with patch 2');
